font_family JetBrainsMono Nerd Font
font_size 11

enable_audio_bell no
visual_bell_duration 0

scrollback_lines 5000

confirm_os_window_close 0

cursor_blink_interval 0

window_padding_width 8

background_opacity 1.0

hide_window_decorations yes

allow_remote_control no

shell_integration enabled

copy_on_select yes
