monitor=,preferred,auto,1

$terminal = kitty
$menu = rofi -show drun

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland,x11
env = ELECTRON_OZONE_PLATFORM_HINT,auto

exec-once = waybar
exec-once = nm-applet
exec-once = /usr/lib/polkit-kde-authentication-agent-1

input {
    kb_layout = us

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 7

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = true

    animation = windows, 1, 3, default
    animation = windowsOut, 1, 3, default
    animation = border, 1, 3, default
    animation = fade, 1, 3, default
    animation = workspaces, 1, 3, default
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 0
}

bind = SUPER, Return, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen
bind = SUPER, V, togglefloating
bind = SUPER, M, exit

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6

bind = XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bind = XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = XF86MonBrightnessDown, exec, brightnessctl set 5%-
